import streamlit as st
import time
from agent import ResearchAgent, export_review
from memory import load_memory

# --- 1. CONFIGURATION ---

# Custom Palate (as requested): 
# bc4749 (Dark Red/Maroon), f2e8cf (Cream/Background), a7c957 (Light Green), 6a994e (Medium Green), 386641 (Dark Green/Accent)
BG_COLOR = "#f2e8cf"
TEXT_COLOR = "#386641"
PRIMARY_COLOR = "#bc4749" 
ACCENT_COLOR = "#a7c957"
HOVER_COLOR = "#6a994e"


# --- 2. CUSTOM CSS & STYLE ---

CUSTOM_STYLE = f"""
<style>
/* --- General Styling / Font / Background --- */
.stApp {{
    background-color: {BG_COLOR}; 
    color: {TEXT_COLOR};
}}
h1, h2, h3, .st-emotion-cache-18ni4af {{
    color: {PRIMARY_COLOR}; /* Main titles */
    font-family: 'Arial', sans-serif;
}}
.st-emotion-cache-16ya5v5 {{ /* Target markdown text in Streamlit */
    color: {TEXT_COLOR} !important;
}}

/* --- Glass Morphism Effect for Containers --- */
.glass-container {{
    background: rgba(255, 255, 255, 0.2); 
    box-shadow: 0 8px 32px 0 rgba(0, 0, 0, 0.1);
    backdrop-filter: blur(4px);
    -webkit-backdrop-filter: blur(4px);
    border-radius: 10px;
    border: 1px solid rgba(255, 255, 255, 0.3);
    padding: 20px;
    margin-bottom: 20px;
}}

/* --- Button Styling with Interactive Hover --- */
div.stButton > button:first-child {{
    background-color: {ACCENT_COLOR};
    color: white;
    font-weight: bold;
    border: none;
    padding: 10px 20px;
    border-radius: 8px;
    transition: background-color 0.3s, box-shadow 0.3s;
}}
div.stButton > button:first-child:hover {{
    background-color: {HOVER_COLOR}; 
    box-shadow: 0 4px 10px rgba(56, 102, 65, 0.5); /* Shadow on hover */
}}

/* --- Custom Scrollbar for the Review Output --- */
.review-output {{
    max-height: 500px; 
    overflow-y: auto; 
    padding-right: 15px;
    border-right: 3px solid {PRIMARY_COLOR}; /* Simple scroll hint */
}}

/* --- Cursor Glow (Complex, applied to body) --- */
/* This is a simple approximation. True cursor glow often requires JavaScript */
body:before {{
    content: '';
    position: fixed;
    top: -100px;
    left: -100px;
    width: 200px;
    height: 200px;
    border-radius: 50%;
    background: radial-gradient(circle, rgba(255, 255, 255, 0.5) 0%, rgba(255, 255, 255, 0) 70%);
    pointer-events: none;
    z-index: 9999;
    transition: all 0.1s ease-out;
    transform: translate(var(--mouse-x), var(--mouse-y));
    opacity: 0.15;
}}
</style>
"""

# Apply the custom styles
st.markdown(CUSTOM_STYLE, unsafe_allow_html=True)


# --- 3. AGENT EXECUTION FUNCTION ---

@st.cache_resource
def get_agent():
    """Initializes and returns the ResearchAgent."""
    return ResearchAgent()

def run_research_process(agent, topic: str):
    """Executes the core research logic and displays output."""
    
    # Use st.spinner for a nice loading indicator
    with st.spinner(f"🔍 Starting research on '{topic}'..."):
        
        # 1. Run the core agent process (reduced to 1 paper for API safety)
        final_output = agent.run_research(topic, paper_limit=1)
        
        if not final_output:
            st.error("🛑 Research failed: Could not retrieve papers or generate summary.")
            return

    st.success("🎉 Research Complete! Review Generated.")
    
    # 2. Display the review in the scrollable container
    st.subheader("📚 Final Literature Review")
    # Wrap output in a div with the custom CSS class
    st.markdown('<div class="review-output glass-container">', unsafe_allow_html=True)
    
    # Display the full Markdown content generated by agent.py
    st.markdown(final_output['markdown_review'], unsafe_allow_html=True)
    
    st.markdown('</div>', unsafe_allow_html=True)

    # 3. Handle the file download button
    st.download_button(
        label="Download Full Review (.md)",
        data=final_output['markdown_review'],
        file_name=f"{topic.lower().replace(' ', '_')}_review.md",
        mime="text/markdown"
    )

# --- 4. STREAMLIT APP LAYOUT ---

def main_app():
    """Main Streamlit application function."""
    
    agent = get_agent()

    # --- Header ---
    st.markdown("<h1>🔬 AI Research Assistant Agent</h1>", unsafe_allow_html=True)
    st.markdown(f'<div class="glass-container">A Streamlit-powered RAG agent using Gemini and Semantic Scholar for academic literature reviews.</div>', unsafe_allow_html=True)

    # --- Input Form ---
    with st.form("research_form", clear_on_submit=False):
        topic = st.text_input(
            "Enter your Research Topic:",
            placeholder="e.g., Explainable AI for Drug Discovery",
            key="input_topic"
        )
        submitted = st.form_submit_button("Run Research Agent")

    # --- Execution ---
    if submitted and topic:
        run_research_process(agent, topic.strip())

    # In app.py
    # --- History (Optional) ---
    # In app.py (around line 168)

    # --- History (Optional) ---
    history_container = st.container()
    with history_container:
        st.subheader("🕰️ Research History")
        # Now this returns List[Dict[str, Any]]
        past_topics = agent.get_history() 
        
        if past_topics:
            st.markdown(f'<div class="glass-container">', unsafe_allow_html=True)
            # Loop over the last 5 entries
            for topic_entry in past_topics[-5:]: 
                st.write(f"- {topic_entry['topic']} (_{time.strftime('%b %d, %Y', time.strptime(topic_entry['date'], '%Y-%m-%d %H:%M:%S'))}_)")
            st.markdown('</div>', unsafe_allow_html=True)
        else:
            st.info("No research history yet.")


if __name__ == "__main__":
    main_app()